name: Deploy BasketBlog

on:
  push:
    branches:
      - main # Replace "main" with your branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Inject TOKEN into BasketBlog.html
      - name: Inject TOKEN into HTML
        run: |
          echo "Injecting TOKEN into BasketBlog.html..."
          sed -i "s|TOKEN_PLACEHOLDER|${{ secrets.TOKEN }}|g" BasketBlog.html

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Use "." if your site files are in the root directory
